name: iac-static-scans

on:
  workflow_call:

jobs:
  trivy-config-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-iac.sarif
          scanners: misconfig,secret
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-iac.sarif

  cis-benchmark:
    runs-on: ubuntu-latest
    container:
      image: docker.io/aquasec/kube-bench:latest
    steps:
      - run: kube-bench --targets node,policies --json > kube-bench.json || true
      - uses: actions/upload-artifact@v4
        with:
          name: kube-bench
          path: kube-bench.json
