name: image-post-build

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  packages: read
  security-events: write

jobs:
  trivy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ inputs.image-ref }}
          format: sarif
          output: trivy-image.sarif
          severity: CRITICAL,HIGH
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif

  cosign-sign:
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@v3
      - env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign --yes ${{ inputs.image-ref }}
